name: Auto Deploy VPN Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 45.92.174.166
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/VPN_GPT
            git fetch --all
            git reset --hard origin/main
            systemctl restart vpn-bot
            systemctl status vpn-bot --no-pager
            echo "✅ VPN Bot successfully redeployed with latest code!"
