name: Auto Deploy VPN Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 45.92.174.166
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/vpn-bot
            git pull origin main
            systemctl restart vpn-bot
            echo "✅ VPN Bot redeployed successfully!"

