name: Validate OpenAPI schema

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  generate-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt openapi-spec-validator

      - name: Generate raw OpenAPI schema
        run: |
          source .venv/bin/activate
          python tools/generate_openapi.py

      - name: Post-process schema for OpenAI Actions
        run: |
          source .venv/bin/activate
          python tools/postprocess_openapi.py openapi_raw.json openapi_gpt.json

      - name: Validate processed schema
        run: |
          source .venv/bin/activate
          openapi-spec-validator openapi_gpt.json

      - name: Upload schema artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi_gpt
          path: openapi_gpt.json
